CREATE TABLE ciclos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
);

CREATE TABLE profesores (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    color_hex TEXT DEFAULT '#3388ff',
    horas_max_dia INT DEFAULT 6,
    horas_max_semana INT DEFAULT 20
);

CREATE TABLE modulos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    ciclo_id INT REFERENCES ciclos(id) ON DELETE CASCADE,
    horas_semanales INT NOT NULL,
    horas_max_dia INT DEFAULT 3
);

CREATE TABLE competencia_profesor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id INT REFERENCES profesores(id) ON DELETE CASCADE,
    modulo_id INT REFERENCES modulos(id) ON DELETE CASCADE,
    UNIQUE(profesor_id, modulo_id) -- Evita duplicados
);

CREATE TABLE preferencias (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id INT REFERENCES profesores(id) ON DELETE CASCADE,
    dia_semana INT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    nivel_prioridad INT NOT NULL CHECK (nivel_prioridad IN (0, 1, 2)), --Validacion de prioridad
    motivo TEXT
    CONSTRAINT check_horas_pref CHECK (hora_fin > hora_inicio) --Validacion de horas
);

CREATE TABLE horario_generado (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id INT REFERENCES profesores(id) ON DELETE SET NULL,
    modulo_id INT REFERENCES modulos(id) ON DELETE CASCADE,
    dia_semana INT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    version_horario INT DEFAULT 1
    CONSTRAINT check_horas_horario CHECK (hora_fin > hora_inicio) --Validacion de horas
);