CREATE TABLE profesores (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    color_hex TEXT DEFAULT '#3388ff',
    horas_max_dia INT DEFAULT 6,
    horas_max_semana INT DEFAULT 20
);

CREATE TABLE modulos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    ciclo TEXT NOT NULL,
    horas_semanales INT NOT NULL,
    horas_max_dia INT DEFAULT 3
);

CREATE TABLE competencia_profesor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id INT REFERENCES profesores(id) ON DELETE CASCADE,
    modulo_id INT REFERENCES modulos(id) ON DELETE CASCADE,
    UNIQUE(profesor_id, modulo_id) -- Evita duplicados
);

CREATE TABLE preferencias (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id INT REFERENCES profesores(id) ON DELETE CASCADE,
    dia_semana INT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    nivel_prioridad INT NOT NULL,
    motivo TEXT
);

CREATE TABLE horario_generado (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id INT REFERENCES profesores(id) ON DELETE SET NULL,
    modulo_id INT REFERENCES modulos(id) ON DELETE CASCADE,
    dia_semana INT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    version_horario INT DEFAULT 1
);